export type TypographyToken = {
  displayName: string
  group: string
  name: string
  numericValue?: string
  remValue?: string
  type: 'fontFamily' | 'fontWeight' | 'fontSize' | 'lineHeight'
  value: string
}

export const typographyTokens = [
  {
    name: 'Family/font-family',
    displayName: 'font-family',
    group: 'Family',
    type: 'fontFamily',
    value: 'Barlow',
  },
  {
    name: 'Family/font-family-brand',
    displayName: 'font-family-brand',
    group: 'Family',
    type: 'fontFamily',
    value: 'BlinkXSans New',
  },
  {
    name: 'Font weight/regular',
    displayName: 'regular',
    group: 'Font weight',
    type: 'fontWeight',
    value: 'Regular',
    numericValue: '400',
  },
  {
    name: 'Font weight/medium',
    displayName: 'medium',
    group: 'Font weight',
    type: 'fontWeight',
    value: 'Medium',
    numericValue: '500',
  },
  {
    name: 'Font weight/semiBold',
    displayName: 'semiBold',
    group: 'Font weight',
    type: 'fontWeight',
    value: 'SemiBold',
    numericValue: '600',
  },
  {
    name: 'Font weight/bold',
    displayName: 'bold',
    group: 'Font weight',
    type: 'fontWeight',
    value: 'Bold',
    numericValue: '700',
  },
  {
    name: 'size/display/display',
    displayName: 'display/display',
    group: 'Size',
    type: 'fontSize',
    value: '32px',
    remValue: '2rem',
  },
  {
    name: 'size/h1/text-4xl',
    displayName: 'h1/text-4xl',
    group: 'Size',
    type: 'fontSize',
    value: '28px',
    remValue: '1.75rem',
  },
  {
    name: 'size/h2/text-3xl',
    displayName: 'h2/text-3xl',
    group: 'Size',
    type: 'fontSize',
    value: '24px',
    remValue: '1.5rem',
  },
  {
    name: 'size/h3/text-2xl',
    displayName: 'h3/text-2xl',
    group: 'Size',
    type: 'fontSize',
    value: '20px',
    remValue: '1.25rem',
  },
  {
    name: 'size/h4/text-xl',
    displayName: 'h4/text-xl',
    group: 'Size',
    type: 'fontSize',
    value: '18px',
    remValue: '1.125rem',
  },
  {
    name: 'size/h5/text-lg',
    displayName: 'h5/text-lg',
    group: 'Size',
    type: 'fontSize',
    value: '16px',
    remValue: '1rem',
  },
  {
    name: 'size/h6/text-md',
    displayName: 'h6/text-md',
    group: 'Size',
    type: 'fontSize',
    value: '14px',
    remValue: '0.875rem',
  },
  {
    name: 'size/body/text-sm',
    displayName: 'body/text-sm',
    group: 'Size',
    type: 'fontSize',
    value: '12px',
    remValue: '0.75rem',
  },
  {
    name: 'size/label-1/text-xs',
    displayName: 'label-1/text-xs',
    group: 'Size',
    type: 'fontSize',
    value: '11px',
    remValue: '0.6875rem',
  },
  {
    name: 'size/label-2/text-xxs',
    displayName: 'label-2/text-xxs',
    group: 'Size',
    type: 'fontSize',
    value: '10px',
    remValue: '0.625rem',
  },
  {
    name: 'Line height/display/display',
    displayName: 'display/display',
    group: 'Line height',
    type: 'lineHeight',
    value: '40px',
    remValue: '2.5rem',
  },
  {
    name: 'Line height/h1/text-4xl',
    displayName: 'h1/text-4xl',
    group: 'Line height',
    type: 'lineHeight',
    value: '36px',
    remValue: '2.25rem',
  },
  {
    name: 'Line height/h2/text-3xl',
    displayName: 'h2/text-3xl',
    group: 'Line height',
    type: 'lineHeight',
    value: '32px',
    remValue: '2rem',
  },
  {
    name: 'Line height/h3/text-2xl',
    displayName: 'h3/text-2xl',
    group: 'Line height',
    type: 'lineHeight',
    value: '28px',
    remValue: '1.75rem',
  },
  {
    name: 'Line height/h4/text-lg',
    displayName: 'h4/text-lg',
    group: 'Line height',
    type: 'lineHeight',
    value: '24px',
    remValue: '1.5rem',
  },
  {
    name: 'Line height/h5/display',
    displayName: 'h5/display',
    group: 'Line height',
    type: 'lineHeight',
    value: '24px',
    remValue: '1.5rem',
  },
  {
    name: 'Line height/h6/display',
    displayName: 'h6/display',
    group: 'Line height',
    type: 'lineHeight',
    value: '20px',
    remValue: '1.25rem',
  },
  {
    name: 'Line height/body/text-sm',
    displayName: 'body/text-sm',
    group: 'Line height',
    type: 'lineHeight',
    value: '16px',
    remValue: '1rem',
  },
  {
    name: 'Line height/label-1/text-xs',
    displayName: 'label-1/text-xs',
    group: 'Line height',
    type: 'lineHeight',
    value: '16px',
    remValue: '1rem',
  },
  {
    name: 'Line height/label-2/text-xxs',
    displayName: 'label-2/text-xxs',
    group: 'Line height',
    type: 'lineHeight',
    value: '16px',
    remValue: '1rem',
  },
] satisfies TypographyToken[]
