export type SpacingToken = {
  aliasTo: string
  displayName: string
  group: string
  name: string
  remValue: string
  value: string
}

export const spacingTokens = [
  {
    name: 'spacing-none',
    displayName: 'spacing-none',
    group: 'Spacing',
    value: '0px',
    remValue: '0rem',
    aliasTo: 'unit/0',
  },
  {
    name: 'spacing-xxs',
    displayName: 'spacing-xxs',
    group: 'Spacing',
    value: '1px',
    remValue: '0.0625rem',
    aliasTo: 'unit/1',
  },
  {
    name: 'spacing-xs',
    displayName: 'spacing-xs',
    group: 'Spacing',
    value: '2px',
    remValue: '0.125rem',
    aliasTo: 'unit/2',
  },
  {
    name: 'spacing-sm',
    displayName: 'spacing-sm',
    group: 'Spacing',
    value: '4px',
    remValue: '0.25rem',
    aliasTo: 'unit/4',
  },
  {
    name: 'spacing-md',
    displayName: 'spacing-md',
    group: 'Spacing',
    value: '6px',
    remValue: '0.375rem',
    aliasTo: 'unit/6',
  },
  {
    name: 'spacing-lg',
    displayName: 'spacing-lg',
    group: 'Spacing',
    value: '8px',
    remValue: '0.5rem',
    aliasTo: 'unit/8',
  },
  {
    name: 'spacing-xl',
    displayName: 'spacing-xl',
    group: 'Spacing',
    value: '12px',
    remValue: '0.75rem',
    aliasTo: 'unit/12',
  },
  {
    name: 'spacing-2xl',
    displayName: 'spacing-2xl',
    group: 'Spacing',
    value: '16px',
    remValue: '1rem',
    aliasTo: 'unit/16',
  },
  {
    name: 'spacing-3xl',
    displayName: 'spacing-3xl',
    group: 'Spacing',
    value: '20px',
    remValue: '1.25rem',
    aliasTo: 'unit/20',
  },
  {
    name: 'spacing-4xl',
    displayName: 'spacing-4xl',
    group: 'Spacing',
    value: '24px',
    remValue: '1.5rem',
    aliasTo: 'unit/24',
  },
  {
    name: 'spacing-5xl',
    displayName: 'spacing-5xl',
    group: 'Spacing',
    value: '28px',
    remValue: '1.75rem',
    aliasTo: 'unit/28',
  },
  {
    name: 'spacing-6xl',
    displayName: 'spacing-6xl',
    group: 'Spacing',
    value: '32px',
    remValue: '2rem',
    aliasTo: 'unit/32',
  },
  {
    name: 'spacing-7xl',
    displayName: 'spacing-7xl',
    group: 'Spacing',
    value: '38px',
    remValue: '2.375rem',
    aliasTo: 'unit/38',
  },
  {
    name: 'spacing-8xl',
    displayName: 'spacing-8xl',
    group: 'Spacing',
    value: '40px',
    remValue: '2.5rem',
    aliasTo: 'unit/40',
  },
  {
    name: 'spacing-9xl',
    displayName: 'spacing-9xl',
    group: 'Spacing',
    value: '48px',
    remValue: '3rem',
    aliasTo: 'unit/48',
  },
  {
    name: 'spacing-10xl',
    displayName: 'spacing-10xl',
    group: 'Spacing',
    value: '52px',
    remValue: '3.25rem',
    aliasTo: 'unit/52',
  },
  {
    name: 'spacing-11xl',
    displayName: 'spacing-11xl',
    group: 'Spacing',
    value: '56px',
    remValue: '3.5rem',
    aliasTo: 'unit/56',
  },
  {
    name: 'spacing-12xl',
    displayName: 'spacing-12xl',
    group: 'Spacing',
    value: '64px',
    remValue: '4rem',
    aliasTo: 'unit/64',
  },
  {
    name: 'spacing-13xl',
    displayName: 'spacing-13xl',
    group: 'Spacing',
    value: '72px',
    remValue: '4.5rem',
    aliasTo: 'unit/72',
  },
  {
    name: 'spacing-14xl',
    displayName: 'spacing-14xl',
    group: 'Spacing',
    value: '80px',
    remValue: '5rem',
    aliasTo: 'unit/80',
  },
] satisfies SpacingToken[]
